### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by FoRRestDp** [mitchtabian/Food2Fork-KMM#1]
Error message:

FAILURE: Build failed with an exception.

* Where:
Build file '~/Food2Fork-KMM/androidFood2Fork/build.gradle.kts' line: 1

* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 6.8.2. Current version is 6.5. If using the gradle wrapper, try editing the distributionUrl in ~/Food2Fork-KMM/gradle/wrapper/gradle-wrapper.properties to gradle-6.8.2-all.zip

**Comment by codejunk1e** [comment]
Faced this issue too the gradle wrapper files and contents are missing @mitchtabian

**Comment by mitchtabian** [comment]
Oh woops I ignored. I'll fix by Monday
