### ISSUE TITLE
SwiftUI previews not working

### ISSUE THREAD

**Issue by cgaisl** [mitchtabian/Food2Fork-KMM#2]
Do I have to do anything special to get the SwiftUI previews working? Any preview of a view that uses a Type defined in the shared coded crashes for me (RecipeCard.swift for instance). At first it says that it took more than 5 seconds, and after a few tries it crashes.

**Comment by mitchtabian** [comment]
For most of the swiftUI previews I just commented them out. I was having problems also and I'm a shit iOS developer so didn't look into it much.
