### ISSUE TITLE
How to join your discord server.

### ISSUE THREAD

**Issue by EGOR-IND** [mitchtabian/Food2Fork-KMM#5]
Dear sir,
I'm following you for around 3-4 months and I want to join your discord server. I have some doubts regarding Ktor, so I thought that by joining your discord server I'll get some help:).

**Comment by EGOR-IND** [comment]
Hey @mitchtabian, can you tell me how to upload an image by making a multipart request using ktor client for android.

**Comment by mitchtabian** [comment]
There is a link in your profile on codingwithmitch.com
