### ISSUE TITLE
Cannot run project on AS Arctic Fox 2020.3.1 Beta 3 

### ISSUE THREAD

**Issue by GianlucaVeschi** [mitchtabian/Food2Fork-KMM#6]
After downloading the project I am required to update 

`private const val gradleBuildTools = "7.0.0-alpha09" `to `"7.0.0-beta04"`

but this causes the following exception 
```
* Exception is:
org.gradle.api.GradleException: Please initialize at least one Kotlin target in 'shared (:shared)'.
Read more https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#setting-up-targets
	at org.jetbrains.kotlin.gradle.plugin.KotlinMultiplatformPluginWrapper.whenBuildEvaluated(KotlinPluginWrapper.kt:217)
	at org.jetbrains.kotlin.gradle.plugin.KotlinBasePluginWrapper$apply$1.execute(KotlinPluginWrapper.kt:68)
	at org.jetbrains.kotlin.gradle.plugin.KotlinBasePluginWrapper$apply$1.execute(KotlinPluginWrapper.kt:67)
```

I just went through the `README` file again and noticed that this project was built on an older version of AS. It would be cool to know which dependencies have to be updated in order to be able to run the project on the latest beta version.

<img width="1792" alt="grafik" src="https://user-images.githubusercontent.com/19254758/123234492-45dd7600-d4db-11eb-9249-ba092e8eac80.png">

**Comment by mitchtabian** [comment]
If you want to use the newest android studio version you'll need to solve some conflicts. Otherwise use the same version I did as stated in the readme and in th course videos

**Comment by RdeWilde** [comment]
@mitchtabian any clue where these conflicts reside? I have the same error in my project, although it is different source code than yours

**Comment by manu0396** [comment]
Some update about this error?? I have KMM proyect which compiles fine, but after upgrade some dependecies, start to get this error and i'm not able to fix it.
